version: 2

linters:
  enable:
    - errcheck
    - ineffassign
    - bodyclose
    - noctx
    - staticcheck
    - unused
    - unconvert
    - revive
    - gocritic
    - govet
    - misspell
    - godot
    - prealloc
    - gosec

formatters:
  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - event-api # ← теперь массив

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    tab:
      path: stdout

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
