// Package grpcserver provides gRPC types generated from proto.
// This file contains manual type definitions that would normally be generated by protoc.
// In a real project, run: protoc --go_out=. --go-grpc_out=. api/proto/telegram_service.proto
package grpcserver

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
)

// Request/Response types matching the proto definitions
// JSON tags must match the client-side types (snake_case)

type GenerateBindingLinkRequest struct {
	UserId string `json:"user_id"`
}

type GenerateBindingLinkResponse struct {
	Success       bool   `json:"success"`
	ErrorCode     string `json:"error_code"`
	ErrorMessage  string `json:"error_message"`
	Deeplink      string `json:"deeplink"`
	Token         string `json:"token"`
	Code          string `json:"code"` // Short 6-character code for manual entry
	ExpiresAtUnix int64  `json:"expires_at_unix"`
}

type SendVerificationCodeRequest struct {
	UserId           string `json:"user_id"`
	Code             string `json:"code"`
	ExpiresInMinutes int32  `json:"expires_in_minutes"`
}

type SendVerificationCodeResponse struct {
	Success      bool   `json:"success"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
	SentAtUnix   int64  `json:"sent_at_unix"`
	MessageId    string `json:"message_id"`
}

type SendEventReminderRequest struct {
	UserId           string `json:"user_id"`
	EventId          string `json:"event_id"`
	EventTitle       string `json:"event_title"`
	EventDescription string `json:"event_description"`
	EventStartUnix   int64  `json:"event_start_unix"`
	EventLocation    string `json:"event_location"`
	DeeplinkUrl      string `json:"deeplink_url"`
}

type SendEventReminderResponse struct {
	Success      bool   `json:"success"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
	SentAtUnix   int64  `json:"sent_at_unix"`
	MessageId    string `json:"message_id"`
}

type SendMessageRequest struct {
	UserId          string `json:"user_id"`
	Text            string `json:"text"`
	ParseMode       string `json:"parse_mode"`
	Silent          bool   `json:"silent"`
	ReplyMarkupJson string `json:"reply_markup_json"`
}

type SendMessageResponse struct {
	Success      bool   `json:"success"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
	SentAtUnix   int64  `json:"sent_at_unix"`
	MessageId    string `json:"message_id"`
}

type IsUserBoundRequest struct {
	UserId string `json:"user_id"`
}

type IsUserBoundResponse struct {
	Success      bool   `json:"success"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
	IsBound      bool   `json:"is_bound"`
	Status       string `json:"status"`
}

type GetBindingStatusRequest struct {
	UserId string `json:"user_id"`
}

type GetBindingStatusResponse struct {
	Success           bool   `json:"success"`
	ErrorCode         string `json:"error_code"`
	ErrorMessage      string `json:"error_message"`
	Status            string `json:"status"`
	TelegramUsername  string `json:"telegram_username"`
	TelegramFirstName string `json:"telegram_first_name"`
	TelegramLastName  string `json:"telegram_last_name"`
	ChatId            int64  `json:"chat_id"`
	CreatedAtUnix     int64  `json:"created_at_unix"`
	UpdatedAtUnix     int64  `json:"updated_at_unix"`
	BlockedReason     string `json:"blocked_reason"`
}

type UnbindUserRequest struct {
	UserId string `json:"user_id"`
	Reason string `json:"reason"`
}

type UnbindUserResponse struct {
	Success      bool   `json:"success"`
	ErrorCode    string `json:"error_code"`
	ErrorMessage string `json:"error_message"`
}

// TelegramServiceServer is the server API for TelegramService service.
type TelegramServiceInterface interface {
	GenerateBindingLink(context.Context, *GenerateBindingLinkRequest) (*GenerateBindingLinkResponse, error)
	SendVerificationCode(context.Context, *SendVerificationCodeRequest) (*SendVerificationCodeResponse, error)
	SendEventReminder(context.Context, *SendEventReminderRequest) (*SendEventReminderResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	IsUserBound(context.Context, *IsUserBoundRequest) (*IsUserBoundResponse, error)
	GetBindingStatus(context.Context, *GetBindingStatusRequest) (*GetBindingStatusResponse, error)
	UnbindUser(context.Context, *UnbindUserRequest) (*UnbindUserResponse, error)
}

// UnimplementedTelegramServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTelegramServiceServer struct{}

func (UnimplementedTelegramServiceServer) GenerateBindingLink(context.Context, *GenerateBindingLinkRequest) (*GenerateBindingLinkResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendVerificationCode(context.Context, *SendVerificationCodeRequest) (*SendVerificationCodeResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendEventReminder(context.Context, *SendEventReminderRequest) (*SendEventReminderResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) IsUserBound(context.Context, *IsUserBoundRequest) (*IsUserBoundResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) GetBindingStatus(context.Context, *GetBindingStatusRequest) (*GetBindingStatusResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) UnbindUser(context.Context, *UnbindUserRequest) (*UnbindUserResponse, error) {
	return nil, nil
}

// RegisterTelegramServiceServer registers the service with the gRPC server.
// Note: In production, use generated code from protoc-gen-go-grpc.
func RegisterTelegramServiceServer(s *grpc.Server, srv *TelegramServiceServer) {
	// This is a simplified registration. In production, use generated code.
	// The actual implementation would register method handlers.
	s.RegisterService(&_TelegramService_serviceDesc, srv)
}

var _TelegramService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telegram.v1.TelegramService",
	HandlerType: (*TelegramServiceInterface)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateBindingLink",
			Handler:    _TelegramService_GenerateBindingLink_Handler,
		},
		{
			MethodName: "SendVerificationCode",
			Handler:    _TelegramService_SendVerificationCode_Handler,
		},
		{
			MethodName: "SendEventReminder",
			Handler:    _TelegramService_SendEventReminder_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _TelegramService_SendMessage_Handler,
		},
		{
			MethodName: "IsUserBound",
			Handler:    _TelegramService_IsUserBound_Handler,
		},
		{
			MethodName: "GetBindingStatus",
			Handler:    _TelegramService_GetBindingStatus_Handler,
		},
		{
			MethodName: "UnbindUser",
			Handler:    _TelegramService_UnbindUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/telegram_service.proto",
}

func _TelegramService_GenerateBindingLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBindingLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).GenerateBindingLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/GenerateBindingLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).GenerateBindingLink(ctx, req.(*GenerateBindingLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendVerificationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendVerificationCode(ctx, req.(*SendVerificationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendEventReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendEventReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendEventReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendEventReminder(ctx, req.(*SendEventReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_IsUserBound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserBoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).IsUserBound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/IsUserBound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).IsUserBound(ctx, req.(*IsUserBoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_GetBindingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBindingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).GetBindingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/GetBindingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).GetBindingStatus(ctx, req.(*GetBindingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_UnbindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).UnbindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/UnbindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).UnbindUser(ctx, req.(*UnbindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// jsonCodec implements grpc.Codec for JSON encoding.
// This allows using plain structs instead of proto.Message types.
type jsonCodec struct{}

func (jsonCodec) Marshal(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

func (jsonCodec) Unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

func (jsonCodec) Name() string {
	return "json"
}

// JSONCodecOption returns a server option that uses JSON instead of protobuf.
func JSONCodecOption() grpc.ServerOption {
	return grpc.ForceServerCodec(jsonCodec{})
}
