// Package grpcserver provides gRPC types generated from proto.
// This file contains manual type definitions that would normally be generated by protoc.
// In a real project, run: protoc --go_out=. --go-grpc_out=. api/proto/telegram_service.proto
package grpcserver

import (
	"context"

	"google.golang.org/grpc"
)

// Request/Response types matching the proto definitions

type GenerateBindingLinkRequest struct {
	UserId string
}

type GenerateBindingLinkResponse struct {
	Success       bool
	ErrorCode     string
	ErrorMessage  string
	Deeplink      string
	Token         string
	ExpiresAtUnix int64
}

type SendVerificationCodeRequest struct {
	UserId           string
	Code             string
	ExpiresInMinutes int32
}

type SendVerificationCodeResponse struct {
	Success      bool
	ErrorCode    string
	ErrorMessage string
	SentAtUnix   int64
	MessageId    string
}

type SendEventReminderRequest struct {
	UserId           string
	EventId          string
	EventTitle       string
	EventDescription string
	EventStartUnix   int64
	EventLocation    string
	DeeplinkUrl      string
}

type SendEventReminderResponse struct {
	Success      bool
	ErrorCode    string
	ErrorMessage string
	SentAtUnix   int64
	MessageId    string
}

type SendMessageRequest struct {
	UserId          string
	Text            string
	ParseMode       string
	Silent          bool
	ReplyMarkupJson string
}

type SendMessageResponse struct {
	Success      bool
	ErrorCode    string
	ErrorMessage string
	SentAtUnix   int64
	MessageId    string
}

type IsUserBoundRequest struct {
	UserId string
}

type IsUserBoundResponse struct {
	Success      bool
	ErrorCode    string
	ErrorMessage string
	IsBound      bool
	Status       string
}

type GetBindingStatusRequest struct {
	UserId string
}

type GetBindingStatusResponse struct {
	Success           bool
	ErrorCode         string
	ErrorMessage      string
	Status            string
	TelegramUsername  string
	TelegramFirstName string
	TelegramLastName  string
	ChatId            int64
	CreatedAtUnix     int64
	UpdatedAtUnix     int64
	BlockedReason     string
}

type UnbindUserRequest struct {
	UserId string
	Reason string
}

type UnbindUserResponse struct {
	Success      bool
	ErrorCode    string
	ErrorMessage string
}

// TelegramServiceServer is the server API for TelegramService service.
type TelegramServiceInterface interface {
	GenerateBindingLink(context.Context, *GenerateBindingLinkRequest) (*GenerateBindingLinkResponse, error)
	SendVerificationCode(context.Context, *SendVerificationCodeRequest) (*SendVerificationCodeResponse, error)
	SendEventReminder(context.Context, *SendEventReminderRequest) (*SendEventReminderResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	IsUserBound(context.Context, *IsUserBoundRequest) (*IsUserBoundResponse, error)
	GetBindingStatus(context.Context, *GetBindingStatusRequest) (*GetBindingStatusResponse, error)
	UnbindUser(context.Context, *UnbindUserRequest) (*UnbindUserResponse, error)
}

// UnimplementedTelegramServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTelegramServiceServer struct{}

func (UnimplementedTelegramServiceServer) GenerateBindingLink(context.Context, *GenerateBindingLinkRequest) (*GenerateBindingLinkResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendVerificationCode(context.Context, *SendVerificationCodeRequest) (*SendVerificationCodeResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendEventReminder(context.Context, *SendEventReminderRequest) (*SendEventReminderResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) IsUserBound(context.Context, *IsUserBoundRequest) (*IsUserBoundResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) GetBindingStatus(context.Context, *GetBindingStatusRequest) (*GetBindingStatusResponse, error) {
	return nil, nil
}

func (UnimplementedTelegramServiceServer) UnbindUser(context.Context, *UnbindUserRequest) (*UnbindUserResponse, error) {
	return nil, nil
}

// RegisterTelegramServiceServer registers the service with the gRPC server.
// Note: In production, use generated code from protoc-gen-go-grpc.
func RegisterTelegramServiceServer(s *grpc.Server, srv *TelegramServiceServer) {
	// This is a simplified registration. In production, use generated code.
	// The actual implementation would register method handlers.
	s.RegisterService(&_TelegramService_serviceDesc, srv)
}

var _TelegramService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telegram.v1.TelegramService",
	HandlerType: (*TelegramServiceInterface)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateBindingLink",
			Handler:    _TelegramService_GenerateBindingLink_Handler,
		},
		{
			MethodName: "SendVerificationCode",
			Handler:    _TelegramService_SendVerificationCode_Handler,
		},
		{
			MethodName: "SendEventReminder",
			Handler:    _TelegramService_SendEventReminder_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _TelegramService_SendMessage_Handler,
		},
		{
			MethodName: "IsUserBound",
			Handler:    _TelegramService_IsUserBound_Handler,
		},
		{
			MethodName: "GetBindingStatus",
			Handler:    _TelegramService_GetBindingStatus_Handler,
		},
		{
			MethodName: "UnbindUser",
			Handler:    _TelegramService_UnbindUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/telegram_service.proto",
}

func _TelegramService_GenerateBindingLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBindingLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).GenerateBindingLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/GenerateBindingLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).GenerateBindingLink(ctx, req.(*GenerateBindingLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendVerificationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendVerificationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendVerificationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendVerificationCode(ctx, req.(*SendVerificationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendEventReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendEventReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendEventReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendEventReminder(ctx, req.(*SendEventReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_IsUserBound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserBoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).IsUserBound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/IsUserBound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).IsUserBound(ctx, req.(*IsUserBoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_GetBindingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBindingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).GetBindingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/GetBindingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).GetBindingStatus(ctx, req.(*GetBindingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_UnbindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceInterface).UnbindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegram.v1.TelegramService/UnbindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceInterface).UnbindUser(ctx, req.(*UnbindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}
