linters:
  enable:
    - golint
    - govet
    - errcheck
    - staticcheck
    - gocyclo
    - unused
    - revive
  disable:
    - gocyclo
  issues:
    exclude:
      - "Error return value is not checked"
      - "SA9003" # ignore unused struct fields
  run:
    timeout: 5s
    tests: true
    skip-dirs:
      - "tests"
  output:
    format: json
    path: "lint_report.json"
